baseurl = "http://blog.takady.net/"
languageCode = "ja"
hasCJKLanguage = "true"
title = "Yuichi Takada"
copyright = "&copy; Copyright Yuichi Takada"
theme = "vienna"

[permalinks]
    post = "/blog/:year/:month/:day/:filename/"

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    twitter = "takady7"
    github = "takady"
    linkedin = "takady"
    stackoverflow = "4319579"
    # instagram = "takady7"
    # Disqus shortname
    disqus = "blog-takady-net"
    # Google Analytics API key.
    ga_api_key = "UA-56996369-1"
    # Mixpanel API key.
    author = "Yuichi Takada"
    avatar = "/images/avatar.png"
    #contact = "https://twitter.com/takady7"
    bio = "Tokyo based software engineer."
    # Short subtitle/tagline. This is displayed in the header.
    #subtitle = "Ruby, Rails and something about tech."
    themecolor = "#333" # Defines the tab color in Chrome for Android.
    description = "This is my tech blog."
